(defun howdoyou-google-search (query)
  (let ((url-request-method "GET")
        (url "https://www.google.com/search")
        (args (concat "?q="
                      (url-hexify-string "site:stackoverflow.com ")
                      (url-hexify-string query))))
    (message "%s" args)
    (url-retrieve (concat url args)
                  (lambda (status)
                    (switch-to-buffer (current-buffer))
                    (let ((dom (libxml-parse-html-region (point-min) (point-max))))
                      (erase-buffer)
                      (shr-insert-document dom)))
                  nil t t)))
